# Setup
title: "New"                   # The title of your site
description: "A design and research lab based out of the West End of Toronto."   # A brief description of your site
url: ""              # Your site's full URL
baseurl: ""                                # Leave empty if your site is at root
image: "/assets/images/garden.jpg"          # Default share image path
author: "New"                        # Your name

# Assets
sass:
  sass_dir: _sass
  style: compressed

# About/contact
author:
  name: "New"
  url: ""
  email: "email@newsystems.ca"

# Custom vars
version: 3.0.0


plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-feed  

# Markdown Processing
markdown: kramdown
kramdown:
  footnote_backlink: "â†©"

#Slug adjustment
permalink: /:title/